export const ACTION_LOAD_GIPHY_LIST_REQUESTED = 'ACTION_LOAD_GIPHY_LIST_REQUESTED';
export const ACTION_LOAD_GIPHY_LIST_STARTED = 'ACTION_LOAD_GIPHY_LIST_STARTED';
export const ACTION_LOAD_GIPHY_LIST_SUCCESS = 'ACTION_LOAD_GIPHY_LIST_SUCCESS';
export const ACTION_LOAD_GIPHY_LIST_ERROR = 'ACTION_LOAD_GIPHY_LIST_ERROR';

export const ACTION_LOAD_GIPHY_SEARCH_RESULTS_LIST_REQUESTED = 'ACTION_LOAD_GIPHY_SEARCH_RESULTS_LIST_REQUESTED';

export const ACTION_ADD_GIF_TO_FAVORITES_REQUESTED = 'ACTION_ADD_GIF_TO_FAVORITES_REQUESTED';
export const ACTION_ADD_GIF_TO_FAVORITES_STARTED = 'ACTION_ADD_GIF_TO_FAVORITES_STARTED';
export const ACTION_ADD_GIF_TO_FAVORITES_SUCCESS = 'ACTION_ADD_GIF_TO_FAVORITES_SUCCESS';
export const ACTION_ADD_GIF_TO_FAVORITES_ERROR = 'ACTION_ADD_GIF_TO_FAVORITES_ERROR';
